// GENERATED by scripts/generate-image-variants.mjs — do not edit by hand.
// Maps each source image to the narrower variants written beside it.
export const IMAGE_VARIANTS = {
  "/artak-overview.webp": {
    "widths": [
      400,
      600
    ],
    "intrinsic": 800
  },
  "/artak-mission-planning.webp": {
    "widths": [
      400,
      600
    ],
    "intrinsic": 800
  },
  "/artak-roc-drill.webp": {
    "widths": [
      400,
      600
    ],
    "intrinsic": 800
  },
  "/artak-c2.webp": {
    "widths": [
      400,
      600,
      800,
      1200
    ],
    "intrinsic": 1600
  },
  "/artak-in-action-thumb.webp": {
    "widths": [
      400,
      600
    ],
    "intrinsic": 800
  },
  "/artak-c2-thumb.webp": {
    "widths": [
      400,
      600
    ],
    "intrinsic": 800
  },
  "/artak-xr-sdve-thumb.webp": {
    "widths": [
      400,
      600
    ],
    "intrinsic": 800
  }
};
