import SEO from "@/components/SEO";

export default function Privacy() {
  return (
    <div data-testid="privacy-page">
      <SEO title="Privacy Policy" description="Privacy Policy for EolianVR, Inc. — how we collect, use, disclose, and safeguard your information." path="/privacy" />
      <section className="relative pt-32 pb-20 md:pt-40 md:pb-28">
        <div className="absolute inset-0 tactical-grid opacity-20" />
        <div className="relative max-w-[900px] mx-auto px-6 md:px-12">
          <div className="flex items-center gap-3 mb-4"><div className="w-8 h-px bg-[#FF0B1B]" /><span className="font-mono text-xs tracking-[0.2em] text-zinc-500 uppercase">Legal // Privacy</span></div>
          <h1 className="font-heading text-4xl sm:text-5xl font-black uppercase tracking-tighter text-white leading-[0.95]">Privacy Policy</h1>
          <p className="mt-4 font-mono text-xs text-zinc-500 tracking-wider">Effective Date: May 8, 2026</p>
        </div>
      </section>
      <section className="pb-20 md:pb-28">
        <div className="max-w-[900px] mx-auto px-6 md:px-12 space-y-10">
          <p className="text-sm text-zinc-400 leading-relaxed">EolianVR, Inc. ("Eolian," "we," "our," or "us") respects your privacy and is committed to protecting personal information in accordance with applicable U.S. privacy laws and international best practices.</p>
          <div><p className="text-sm text-zinc-400 mb-2">This Privacy Policy explains how we collect, use, disclose, and safeguard information when you interact with:</p><ul className="list-disc list-inside text-sm text-zinc-400 space-y-1 ml-2"><li>our websites, software platforms, demos, communications, events, applications, and related services.</li></ul></div>
          <div><h2 className="font-heading text-lg font-bold text-white uppercase tracking-wide mb-3">1. Information We Collect</h2><h3 className="font-heading text-sm font-semibold text-zinc-300 uppercase tracking-wide mb-2">Personal Information</h3><ul className="list-disc list-inside text-sm text-zinc-400 space-y-1 ml-2 mb-4"><li>Name, Email address, Phone number, Company/organization, Job title, Billing/contact information</li></ul><h3 className="font-heading text-sm font-semibold text-zinc-300 uppercase tracking-wide mb-2">Technical Information</h3><ul className="list-disc list-inside text-sm text-zinc-400 space-y-1 ml-2 mb-4"><li>IP address, Browser type, Device identifiers, Operating system, Website activity, Referral URLs, Cookie identifiers</li></ul><h3 className="font-heading text-sm font-semibold text-zinc-300 uppercase tracking-wide mb-2">Business & Government Inquiry Information</h3><ul className="list-disc list-inside text-sm text-zinc-400 space-y-1 ml-2 mb-4"><li>Procurement inquiries, Proposal submissions, Partnership discussions, Demo requests, Investor inquiries</li></ul><h3 className="font-heading text-sm font-semibold text-zinc-300 uppercase tracking-wide mb-2">Platform Usage Data</h3><p className="text-sm text-zinc-400">Where applicable, software platforms may collect operational telemetry, diagnostics, logs, and user interaction data for security, support, analytics, and platform improvement.</p></div>
          <div><h2 className="font-heading text-lg font-bold text-white uppercase tracking-wide mb-3">2. How We Use Information</h2><p className="text-sm text-zinc-400 mb-2">We may use information to:</p><ul className="list-disc list-inside text-sm text-zinc-400 space-y-1 ml-2"><li>provide and improve Services; respond to inquiries; conduct demonstrations;</li><li>support government or enterprise engagements; process transactions;</li><li>maintain cybersecurity; detect fraud or misuse; comply with legal obligations;</li><li>conduct analytics and performance optimization; support research and development.</li></ul></div>
          <div><h2 className="font-heading text-lg font-bold text-white uppercase tracking-wide mb-3">3. Cookies & Tracking Technologies</h2><p className="text-sm text-zinc-400 mb-3">We may use cookies, analytics tools, session storage, performance monitoring tools, and similar technologies. Users may control cookies through browser settings and applicable consent tools.</p><p className="text-sm text-zinc-400">Depending on jurisdiction, users may have rights to opt out of certain tracking technologies.</p></div>
          <div><h2 className="font-heading text-lg font-bold text-white uppercase tracking-wide mb-3">4. Sharing of Information</h2><p className="text-sm text-zinc-400 mb-2">We may share information with service providers, cloud hosting providers, analytics providers, legal/compliance advisors, government customers or contracting authorities where required, or in connection with mergers, acquisitions, or financing transactions.</p><p className="text-sm text-zinc-400">We do not sell personal information in the traditional sense.</p></div>
          <div><h2 className="font-heading text-lg font-bold text-white uppercase tracking-wide mb-3">5. Data Security</h2><p className="text-sm text-zinc-400">We implement commercially reasonable technical, administrative, and organizational safeguards designed to protect information. However, no system can be guaranteed completely secure.</p></div>
          <div><h2 className="font-heading text-lg font-bold text-white uppercase tracking-wide mb-3">6. Export-Controlled & Sensitive Information</h2><p className="text-sm text-zinc-400">Users should not submit classified information, ITAR-controlled data, CUI, export-controlled technical data, or sensitive operational information through public website forms unless explicitly authorized.</p></div>
          <div><h2 className="font-heading text-lg font-bold text-white uppercase tracking-wide mb-3">7. Your Privacy Rights</h2><p className="text-sm text-zinc-400 mb-2">Depending on your jurisdiction, you may have rights to access, correct, delete personal information, opt out of certain data processing, appeal privacy decisions, or request data portability.</p><p className="text-sm text-zinc-400 mb-2">California residents may have additional rights under the CCPA/CPRA.</p><p className="text-sm text-zinc-400">To exercise rights, contact: <a href="mailto:mike@eolianvr.com" className="text-[#FF0B1B] hover:text-white transition-colors">mike@eolianvr.com</a></p></div>
          <div><h2 className="font-heading text-lg font-bold text-white uppercase tracking-wide mb-3">8. Global Privacy Control (GPC)</h2><p className="text-sm text-zinc-400">Where legally required, we honor recognized browser-based opt-out preference signals, including Global Privacy Control ("GPC").</p></div>
          <div><h2 className="font-heading text-lg font-bold text-white uppercase tracking-wide mb-3">9. Data Retention</h2><p className="text-sm text-zinc-400">We retain information only as long as reasonably necessary for operational purposes, contractual obligations, legal compliance, dispute resolution, or security purposes.</p></div>
          <div><h2 className="font-heading text-lg font-bold text-white uppercase tracking-wide mb-3">10. Third-Party Services</h2><p className="text-sm text-zinc-400">Our Services may integrate with or reference third-party systems. We are not responsible for third-party privacy practices.</p></div>
          <div><h2 className="font-heading text-lg font-bold text-white uppercase tracking-wide mb-3">11. Children's Privacy</h2><p className="text-sm text-zinc-400">Our Services are not directed to children under 13, and we do not knowingly collect personal information from children.</p></div>
          <div><h2 className="font-heading text-lg font-bold text-white uppercase tracking-wide mb-3">12. International Transfers</h2><p className="text-sm text-zinc-400">Information may be processed in the United States or other jurisdictions where our providers operate.</p></div>
          <div><h2 className="font-heading text-lg font-bold text-white uppercase tracking-wide mb-3">13. Changes to this Policy</h2><p className="text-sm text-zinc-400">We may update this Privacy Policy periodically. Updates will be posted with a revised effective date.</p></div>
          <div className="border-t border-zinc-800 pt-8"><h2 className="font-heading text-lg font-bold text-white uppercase tracking-wide mb-3">14. Contact Information</h2><div className="font-mono text-sm text-zinc-400 space-y-1"><p className="text-white font-medium">EolianVR, Inc.</p><p>12577 66th St.</p><p>Largo, FL 33773</p><p><a href="mailto:mike@eolianvr.com" className="text-[#FF0B1B] hover:text-white transition-colors">mike@eolianvr.com</a></p></div></div>
        </div>
      </section>
    </div>
  );
}
